#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 08, 2018 10:20:01 AM



import queue
import requests
import inspect
import json
import setConfig
import CrawlWeb
import SendEmail
import tkinter

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def setConfigs():
    print('mainApp_support.setConfig')
    setConfig.vp_start_gui(root)


def startWork():
    with open("appConfig.json") as appconfig:
        global Config
        Config = json.load(appconfig)
        print(str(Config))
    articles = []
    with open("siteconfig.json") as site:
        webs = json.load(site)
    for web in webs:
        w.Scrolledtext1.insert(tkinter.END, "正在抓取：" + web['sitename'] + '\n')
        w.Scrolledtext1.update()
        articles = CrawlWeb.getContent(web,articles,w,Config[0]['SEEN']);
    filename = CrawlWeb.IOarticle(articles, w, Config[0]['TRANSLATE'])
    CrawlWeb.mdTohtmldoc(filename,Config[0]['DOC'],Config[0]['HTML'])
    if Config[0]['SENDMAIL']:
        if Config[0]['DOC']:
            SendEmail.send_mail(filename[:-3]+".docx",filename[:-3]+".docx",w)
        if Config[0]['MD']:
            SendEmail.send_mail(filename,filename,w)
        if Config[0]['HTML']:
            SendEmail.send_mail(filename[:-3]+".html",filename[:-3]+".html",w)



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import mainApp
    mainApp.vp_start_gui()

