#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 08, 2018 05:32:20 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import setConfig_support

def vp_start_gui(r):
    '''Starting point when module is the main routine.'''
    global val, w1, root
    root = Toplevel(r)
    setConfig_support.set_Tk_var()
    top = __ (root)
    setConfig_support.init(root, top)
    root.mainloop()

w1 = None
def create___(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w1, w_win, rt
    rt = root
    w1 = Toplevel (root)
    setConfig_support.set_Tk_var()
    top = __ (w1)
    setConfig_support.init(w1, top, *args, **kwargs)
    return (w1, top)

def destroy___():
    global w1
    w1.destroy()
    w1 = None


class __:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("600x738+851+150")
        top.title("设置")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.38, rely=0.93, height=33, width=143)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=setConfig_support.Saveconfig)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''保存设置''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Checkbutton1 = Checkbutton(top)
        self.Checkbutton1.place(relx=0.01, rely=0.06, relheight=0.04
                , relwidth=0.33)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(command=setConfig_support.isSendMail)
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify=LEFT)
        self.Checkbutton1.configure(offrelief="flat")
        self.Checkbutton1.configure(text='''发送邮件''')
        self.Checkbutton1.configure(variable=setConfig_support.sendMail)

        self.Checkbutton2 = Checkbutton(top)
        self.Checkbutton2.place(relx=0.01, rely=0.11, relheight=0.04
                , relwidth=0.32)
        self.Checkbutton2.configure(activebackground="#d9d9d9")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(background="#d9d9d9")
        self.Checkbutton2.configure(command=setConfig_support.isTranslate)
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify=LEFT)
        self.Checkbutton2.configure(text='''自动翻译''')
        self.Checkbutton2.configure(variable=setConfig_support.Translate)

        self.Checkbutton3 = Checkbutton(top)
        self.Checkbutton3.place(relx=0.02, rely=0.16, relheight=0.04
                , relwidth=0.32)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(command=setConfig_support.isSeen)
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''自动去重''')
        self.Checkbutton3.configure(variable=setConfig_support.Seen)

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.27, rely=0.24,height=21, relwidth=0.31)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=setConfig_support.email)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.1, rely=0.23, height=26, width=66)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''变更邮箱''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.67, rely=0.24, height=33, width=63)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=setConfig_support.setEmail)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''提交''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.03, rely=0.3, height=26, width=175)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''发送文档格式''')

        self.Checkbutton4 = Checkbutton(top)
        self.Checkbutton4.place(relx=0.3, rely=0.3, relheight=0.04
                , relwidth=0.09)
        self.Checkbutton4.configure(activebackground="#d9d9d9")
        self.Checkbutton4.configure(activeforeground="#000000")
        self.Checkbutton4.configure(background="#d9d9d9")
        self.Checkbutton4.configure(command=setConfig_support.isMd)
        self.Checkbutton4.configure(disabledforeground="#a3a3a3")
        self.Checkbutton4.configure(foreground="#000000")
        self.Checkbutton4.configure(highlightbackground="#d9d9d9")
        self.Checkbutton4.configure(highlightcolor="black")
        self.Checkbutton4.configure(justify=LEFT)
        self.Checkbutton4.configure(text='''MD''')
        self.Checkbutton4.configure(variable=setConfig_support.MD)
        self.Checkbutton4.select()

        self.Checkbutton5 = Checkbutton(top)
        self.Checkbutton5.place(relx=0.43, rely=0.3, relheight=0.04
                , relwidth=0.12)
        self.Checkbutton5.configure(activebackground="#d9d9d9")
        self.Checkbutton5.configure(activeforeground="#000000")
        self.Checkbutton5.configure(background="#d9d9d9")
        self.Checkbutton5.configure(command=setConfig_support.isHTML)
        self.Checkbutton5.configure(disabledforeground="#a3a3a3")
        self.Checkbutton5.configure(foreground="#000000")
        self.Checkbutton5.configure(highlightbackground="#d9d9d9")
        self.Checkbutton5.configure(highlightcolor="black")
        self.Checkbutton5.configure(justify=LEFT)
        self.Checkbutton5.configure(text='''HTML''')
        self.Checkbutton5.configure(variable=setConfig_support.HTML)
        self.Checkbutton5.deselect()

        self.Checkbutton6 = Checkbutton(top)
        self.Checkbutton6.place(relx=0.58, rely=0.3, relheight=0.04
                , relwidth=0.12)
        self.Checkbutton6.configure(activebackground="#d9d9d9")
        self.Checkbutton6.configure(activeforeground="#000000")
        self.Checkbutton6.configure(background="#d9d9d9")
        self.Checkbutton6.configure(command=setConfig_support.isDOC)
        self.Checkbutton6.configure(disabledforeground="#a3a3a3")
        self.Checkbutton6.configure(foreground="#000000")
        self.Checkbutton6.configure(highlightbackground="#d9d9d9")
        self.Checkbutton6.configure(highlightcolor="black")
        self.Checkbutton6.configure(justify=LEFT)
        self.Checkbutton6.configure(text='''DOC''')
        self.Checkbutton6.configure(variable=setConfig_support.DOC)
        self.Checkbutton6.deselect()

        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.1, rely=0.38, relheight=0.54, relwidth=0.8)

        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''增加爬取网站''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=480)

        self.Label3 = Label(self.Labelframe1)
        self.Label3.place(relx=0.1, rely=0.11, height=26, width=65, y=-16)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''网站名''')

        self.Label4 = Label(self.Labelframe1)
        self.Label4.place(relx=0.1, rely=0.21, height=26, width=75, y=-16)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(justify=LEFT)
        self.Label4.configure(text='''起始网址''')

        self.Label5 = Label(self.Labelframe1)
        self.Label5.place(relx=0.1, rely=0.32, height=26, width=109, y=-16)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(justify=LEFT)
        self.Label5.configure(text='''一级列表Xpath''')

        self.Label5_1 = Label(self.Labelframe1)
        self.Label5_1.place(relx=0.06, rely=0.42, height=26, width=109, y=-16)
        self.Label5_1.configure(activebackground="#f9f9f9")
        self.Label5_1.configure(activeforeground="black")
        self.Label5_1.configure(background="#d9d9d9")
        self.Label5_1.configure(disabledforeground="#a3a3a3")
        self.Label5_1.configure(foreground="#000000")
        self.Label5_1.configure(highlightbackground="#d9d9d9")
        self.Label5_1.configure(highlightcolor="black")
        self.Label5_1.configure(justify=LEFT)
        self.Label5_1.configure(text='''拼接网址''')

        self.Label5_1_1 = Label(self.Labelframe1)
        self.Label5_1_1.place(relx=0.06, rely=0.52, height=26, width=109, y=-16)
        self.Label5_1_1.configure(activebackground="#f9f9f9")
        self.Label5_1_1.configure(activeforeground="black")
        self.Label5_1_1.configure(background="#d9d9d9")
        self.Label5_1_1.configure(disabledforeground="#a3a3a3")
        self.Label5_1_1.configure(foreground="#000000")
        self.Label5_1_1.configure(highlightbackground="#d9d9d9")
        self.Label5_1_1.configure(highlightcolor="black")
        self.Label5_1_1.configure(text='''标题Xpath''')

        self.Label5_1_1_1 = Label(self.Labelframe1)
        self.Label5_1_1_1.place(relx=0.07, rely=0.61, height=26, width=109
                , y=-16)
        self.Label5_1_1_1.configure(activebackground="#f9f9f9")
        self.Label5_1_1_1.configure(activeforeground="black")
        self.Label5_1_1_1.configure(background="#d9d9d9")
        self.Label5_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label5_1_1_1.configure(foreground="#000000")
        self.Label5_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label5_1_1_1.configure(highlightcolor="black")
        self.Label5_1_1_1.configure(text='''时间Xpath''')

        self.Label5_1_1_1_1 = Label(self.Labelframe1)
        self.Label5_1_1_1_1.place(relx=0.07, rely=0.69, height=26, width=109
                , y=-16)
        self.Label5_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Label5_1_1_1_1.configure(activeforeground="black")
        self.Label5_1_1_1_1.configure(background="#d9d9d9")
        self.Label5_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label5_1_1_1_1.configure(foreground="#000000")
        self.Label5_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label5_1_1_1_1.configure(highlightcolor="black")
        self.Label5_1_1_1_1.configure(text='''内容Xpath''')

        self.Label6 = Label(self.Labelframe1)
        self.Label6.place(relx=0.1, rely=0.77, height=26, width=79, y=-16)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''作者Xpath''')

        self.Button3 = Button(self.Labelframe1)
        self.Button3.place(relx=0.39, rely=0.89, height=33, width=104, y=-16)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=setConfig_support.setXpath)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''提交抓取规则''')

        self.lab60_ent70 = Entry(self.Labelframe1)
        self.lab60_ent70.place(relx=0.4, rely=0.13,height=21, relwidth=0.38)
        self.lab60_ent70.configure(background="white")
        self.lab60_ent70.configure(disabledforeground="#a3a3a3")
        self.lab60_ent70.configure(font="TkFixedFont")
        self.lab60_ent70.configure(foreground="#000000")
        self.lab60_ent70.configure(highlightbackground="#d9d9d9")
        self.lab60_ent70.configure(highlightcolor="black")
        self.lab60_ent70.configure(insertbackground="black")
        self.lab60_ent70.configure(selectbackground="#c4c4c4")
        self.lab60_ent70.configure(selectforeground="black")
        self.lab60_ent70.configure(textvariable=setConfig_support.sitename)

        self.lab60_ent71 = Entry(self.Labelframe1)
        self.lab60_ent71.place(relx=0.4, rely=0.21,height=21, relwidth=0.38)
        self.lab60_ent71.configure(background="white")
        self.lab60_ent71.configure(disabledforeground="#a3a3a3")
        self.lab60_ent71.configure(font="TkFixedFont")
        self.lab60_ent71.configure(foreground="#000000")
        self.lab60_ent71.configure(highlightbackground="#d9d9d9")
        self.lab60_ent71.configure(highlightcolor="black")
        self.lab60_ent71.configure(insertbackground="black")
        self.lab60_ent71.configure(selectbackground="#c4c4c4")
        self.lab60_ent71.configure(selectforeground="black")
        self.lab60_ent71.configure(textvariable=setConfig_support.starturl)

        self.lab60_ent72 = Entry(self.Labelframe1)
        self.lab60_ent72.place(relx=0.4, rely=0.33,height=21, relwidth=0.38)
        self.lab60_ent72.configure(background="white")
        self.lab60_ent72.configure(disabledforeground="#a3a3a3")
        self.lab60_ent72.configure(font="TkFixedFont")
        self.lab60_ent72.configure(foreground="#000000")
        self.lab60_ent72.configure(highlightbackground="#d9d9d9")
        self.lab60_ent72.configure(highlightcolor="black")
        self.lab60_ent72.configure(insertbackground="black")
        self.lab60_ent72.configure(selectbackground="#c4c4c4")
        self.lab60_ent72.configure(selectforeground="black")
        self.lab60_ent72.configure(textvariable=setConfig_support.listXpath)

        self.lab60_ent73 = Entry(self.Labelframe1)
        self.lab60_ent73.place(relx=0.4, rely=0.43,height=21, relwidth=0.38)
        self.lab60_ent73.configure(background="white")
        self.lab60_ent73.configure(disabledforeground="#a3a3a3")
        self.lab60_ent73.configure(font="TkFixedFont")
        self.lab60_ent73.configure(foreground="#000000")
        self.lab60_ent73.configure(highlightbackground="#d9d9d9")
        self.lab60_ent73.configure(highlightcolor="black")
        self.lab60_ent73.configure(insertbackground="black")
        self.lab60_ent73.configure(selectbackground="#c4c4c4")
        self.lab60_ent73.configure(selectforeground="black")
        self.lab60_ent73.configure(textvariable=setConfig_support.OriginalUrl)

        self.lab60_ent74 = Entry(self.Labelframe1)
        self.lab60_ent74.place(relx=0.39, rely=0.53,height=21, relwidth=0.38)
        self.lab60_ent74.configure(background="white")
        self.lab60_ent74.configure(disabledforeground="#a3a3a3")
        self.lab60_ent74.configure(font="TkFixedFont")
        self.lab60_ent74.configure(foreground="#000000")
        self.lab60_ent74.configure(highlightbackground="#d9d9d9")
        self.lab60_ent74.configure(highlightcolor="black")
        self.lab60_ent74.configure(insertbackground="black")
        self.lab60_ent74.configure(selectbackground="#c4c4c4")
        self.lab60_ent74.configure(selectforeground="black")
        self.lab60_ent74.configure(textvariable=setConfig_support.titleXpath)

        self.lab60_ent75 = Entry(self.Labelframe1)
        self.lab60_ent75.place(relx=0.39, rely=0.61,height=21, relwidth=0.38)
        self.lab60_ent75.configure(background="white")
        self.lab60_ent75.configure(disabledforeground="#a3a3a3")
        self.lab60_ent75.configure(font="TkFixedFont")
        self.lab60_ent75.configure(foreground="#000000")
        self.lab60_ent75.configure(highlightbackground="#d9d9d9")
        self.lab60_ent75.configure(highlightcolor="black")
        self.lab60_ent75.configure(insertbackground="black")
        self.lab60_ent75.configure(selectbackground="#c4c4c4")
        self.lab60_ent75.configure(selectforeground="black")
        self.lab60_ent75.configure(textvariable=setConfig_support.timeXpath)

        self.lab60_ent76 = Entry(self.Labelframe1)
        self.lab60_ent76.place(relx=0.39, rely=0.7,height=21, relwidth=0.38)
        self.lab60_ent76.configure(background="white")
        self.lab60_ent76.configure(disabledforeground="#a3a3a3")
        self.lab60_ent76.configure(font="TkFixedFont")
        self.lab60_ent76.configure(foreground="#000000")
        self.lab60_ent76.configure(highlightbackground="#d9d9d9")
        self.lab60_ent76.configure(highlightcolor="black")
        self.lab60_ent76.configure(insertbackground="black")
        self.lab60_ent76.configure(selectbackground="#c4c4c4")
        self.lab60_ent76.configure(selectforeground="black")
        self.lab60_ent76.configure(textvariable=setConfig_support.contentXpath)

        self.lab60_ent77 = Entry(self.Labelframe1)
        self.lab60_ent77.place(relx=0.39, rely=0.78,height=21, relwidth=0.38)
        self.lab60_ent77.configure(background="white")
        self.lab60_ent77.configure(disabledforeground="#a3a3a3")
        self.lab60_ent77.configure(font="TkFixedFont")
        self.lab60_ent77.configure(foreground="#000000")
        self.lab60_ent77.configure(highlightbackground="#d9d9d9")
        self.lab60_ent77.configure(highlightcolor="black")
        self.lab60_ent77.configure(insertbackground="black")
        self.lab60_ent77.configure(selectbackground="#c4c4c4")
        self.lab60_ent77.configure(selectforeground="black")
        self.lab60_ent77.configure(textvariable=setConfig_support.aurthorXpath)

        self.Button4 = Button(top)
        self.Button4.place(relx=0.55, rely=0.07, height=33, width=173)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#37f754")
        self.Button4.configure(command=setConfig_support.xhelp)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Xpath Helper''')
        self.Button4.configure(width=173)

        self.Label7 = Label(top)
        self.Label7.place(relx=0.52, rely=0.14, height=26, width=212)
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''对网站xpath抓取分析的小工具''')


def main():
    vp_start_gui()



if __name__ == '__main__':
    vp_start_gui()


