#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 12, 2018 03:01:06 PM


import sys
import json
import tkinter
import tkinter.messagebox as meg

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global indexlist
    indexlist = StringVar()

def deletesite():
    index = int(w.Scrolledlistbox1.curselection()[0])
    del siteconfigjson[index]
    w.Scrolledlistbox1.delete(0,tkinter.END)
    for item in siteconfigjson:
        w.Scrolledlistbox1.insert(tkinter.END,item['sitename'])

    print('sitexpathconfigset_support.deletesite')


def savesite():
    with open("siteconfig.json",'w') as c:
        json.dump(siteconfigjson,c)
    meg.showinfo("提示", "已保存")
    print('sitexpathconfigset_support.savesite')


def updatesite():
    meg.showinfo("提示", "暂未开发此功能")
    print('sitexpathconfigset_support.updatesite')


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    with open("siteconfig.json") as sconfig:
        global siteconfigjson
        siteconfigjson = json.load(sconfig)
    for item in siteconfigjson:
        w.Scrolledlistbox1.insert(tkinter.END,item['sitename'])
    w.Scrolledlistbox1.bind("<<ListboxSelect>>", show_site)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def show_site(*arg):
    index = int(w.Scrolledlistbox1.curselection()[0])
    w.Textsite.delete(0.0,tkinter.END)
    w.Textsite.update()
    w.Textsite.insert(0.0,str(siteconfigjson[index]))





if __name__ == '__main__':
    import sitexpathconfigset
    sitexpathconfigset.vp_start_gui()

